import Link from 'next/link';

export default function UserAgreement() {
  const currentYear = new Date().getFullYear();

  return (
    <main className="min-h-screen bg-white text-slate-800 p-8 md:p-24 font-sans">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="text-blue-600 hover:underline mb-8 inline-block">
          ← Back to Home
        </Link>
        
        <h1 className="text-4xl font-bold mb-4">User Agreement</h1>
        <p className="text-slate-500 mb-8">Effective Date: January 1, {currentYear}</p>

        <section className="space-y-8">
          <div>
            <h2 className="text-2xl font-semibold mb-4 text-slate-900">1. Acceptance of Terms</h2>
            <p className="leading-relaxed text-slate-600">
              By interacting with **AI Whatsapp Bot** via the WhatsApp Business API, you agree to be bound by these terms. If you do not agree, please discontinue use of the service immediately.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4 text-slate-900">2. Description of Service</h2>
            <p className="leading-relaxed text-slate-600">
              AI Whatsapp Bot provides automated messaging services using Artificial Intelligence to answer customer inquiries based on specific business Knowledge Bases. We act as a technical intermediary between you and the business entity you are contacting.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4 text-slate-900">3. AI-Generated Content Disclaimer</h2>
            <div className="bg-amber-50 border-l-4 border-amber-400 p-4 my-4">
              <p className="text-amber-800 text-sm leading-relaxed">
                <strong>Important:</strong> Responses are generated by AI. While we strive for accuracy, the bot may occasionally provide incorrect or incomplete information. AI Whatsapp Bot is not liable for actions taken based on automated responses. Always confirm critical information (like pricing or appointments) directly with the business staff.
              </p>
            </div>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4 text-slate-900">4. Prohibited Use</h2>
            <p className="leading-relaxed text-slate-600">Users agree not to:</p>
            <ul className="list-disc ml-6 mt-2 space-y-2 text-slate-600">
              <li>Use the bot for any illegal or unauthorized purpose.</li>
              <li>Attempt to &quot;jailbreak&quot; or manipulate the AI to generate harmful content.</li>
              <li>Spam the service or attempt to disrupt the WhatsApp integration.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4 text-slate-900">5. Limitation of Liability</h2>
            <p className="leading-relaxed text-slate-600">
              In no event shall AI Whatsapp Bot be liable for any indirect, incidental, or consequential damages arising out of your use or inability to use the service.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4 text-slate-900">6. Governing Law</h2>
            <p className="leading-relaxed text-slate-600">
              These terms are governed by the laws of your jurisdiction, without regard to its conflict of law provisions.
            </p>
          </div>

          <footer className="pt-12 border-t border-slate-100 mt-12 text-center">
            <p className="text-sm text-slate-400">
              © {currentYear} AI Whatsapp Bot. All rights reserved.
            </p>
          </footer>
        </section>
      </div>
    </main>
  );
}